# Site settings
title: Roberto Acevedo
email: me@robertoacevedo.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://robertoacevedo.net" # the base hostname & protocol for your site
twitter_username: rxacevedo
github_username:  rxacevedo
coinbase_userid: '549722b8b6f3c3f9c500008a'

# Build settings
markdown: kramdown
