# Site settings
title: Roberto Acevedo
email: me@robertoacevedo.net
description: > # this means to ignore newlines until "baseurl:"
  Another blog about software (predominantly JVM languages), as well 
  as worfklows, lifehacks, and other goodies. Cheers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://robertoacevedo.net" # the base hostname & protocol for your site
twitter_username: rxacevedo
github_username:  rxacevedo
changetip: true

# Build settings
markdown: kramdown
